# Generated by Django 4.2.2 on 2023-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2550)),
                ('education', models.CharField(max_length=2550)),
                ('skills', models.CharField(max_length=2550)),
                ('phone', models.CharField(max_length=2550)),
                ('github', models.CharField(max_length=2550)),
                ('email', models.CharField(max_length=2550)),
                ('linkedin', models.CharField(max_length=2550)),
                ('achievment', models.CharField(max_length=2550)),
            ],
        ),
    ]
